spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security?
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: MYSQL
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  app:
    SECRET_KEY: "432A462D4A614E645267556B586E3272357538782F413F4428472B4B62506553"
